server:
  port: 28888    #当前应用运行端口号

spring:
  application:
    name: didi-demo
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    suffix: .html
    encoding: UTF-8
  mvc:
    static-path-pattern=/static/**:
  datasource:
    url: jdbc:mysql://localhost:3306/aaa
    username: root
    password: lwy0328
    driver-class-name: com.mysql.cj.jdbc.Driver